### ISSUE TITLE
Suggestion: purchase the slide and add to the repo

### ISSUE THREAD

**Issue by kowyo** [HITSZ-OpenAuto/AUTO3002A#1]
[课后习题答案](https://wenku.baidu.com/view/96a7b1c1f6ec4afe04a1b0717fd5360cba1a8da1.html?re=view&_wkts_=1701696740199&needWelcomeRecommand=1)

**Comment by OliverWu515** [comment]
这个也还行
[习题]( https://wenku.baidu.com/view/9806449f54270722192e453610661ed9ad5155da?aggId=96a7b1c1f6ec4afe04a1b0717fd5360cba1a8da1&fr=catalogMain_text_ernie_recall_v1%3Awk_recommend_main_graph&_wkts_=1702802875605)

**Comment by kowyo** [comment]
已完成
